### ISSUE TITLE
Occurs on all channels when extension is toggled.

### ISSUE THREAD

**Issue by ddday** [Mandrenkov/FreshView#5] opened 2021-11-10 02:58 UTC
![chrome_H0tXewqHvt](https://user-images.githubusercontent.com/17088792/141040889-2920770d-040f-4145-b729-e0bd2802ec01.png)

**Comment by Mandrenkov** [comment] 2021-11-20 15:22
Hello,

Can you clarify what exactly occurs on all the channels? Specifically, I'm wondering if it is always the case that exactly two videos from the channel are tiled across the entire Uploads section.

It would also be helpful if you could specify:
1. The name and version of your browser.
2. The browser extensions you currently have installed.

Thanks!

**Comment by Mandrenkov** [comment] 2022-05-28 18:03
Hello,

I've noticed this issue has been open for a while. 🤔

Given that I can't reproduce the bug and no extra context has been provided, I am going to tentatively close the issue.

**Closed as not planned by Mandrenkov** 2022-05-28 18:03 UTC
Labels: bug
